function dydt = radial_MT_ODE_test(t,y, theta_t, TRF_t, TR, m0f, m0s, T1f, T2f, R, T1s, T2s)

theta = theta_t(t);
TRF   = TRF_t(t);
nbar = T2s / TRF / TR;

ct = cos(theta);
st = sin(theta);

A    = [-ct^2/T1f - st^2/T2f - R*m0s,              R*ct*m0f             , m0f*ct/T1f;...
                R*ct*m0s            , - (1/T1s + R*m0f + nbar*4),   m0s/T1s ;...
                   0                ,                 0                 ,      0    ];

dAdx = [    0     ,      R*ct       ,     ct/T1f   ;... % dAdm0f
            0     ,       -R        ,        0     ;...
            0     ,        0        ,        0     ;...
           -R     ,        0        ,        0     ;... % dAdm0s
          R*ct    ,        0        ,      1/T1s   ;...
            0     ,        0        ,        0     ;...
        ct^2/T1f^2,        0        , -m0f*ct/T1f^2;... % dAdT1f
            0     ,        0        ,        0     ;...
            0     ,        0        ,        0     ;...
        st^2/T2f^2,        0        ,        0     ;... % dAdT2f
            0     ,        0        ,        0     ;...
            0     ,        0        ,        0     ;...
          -m0s    ,     ct*m0f      ,        0     ;... % dAdR
         ct*m0s   ,      -m0f       ,        0     ;...
            0     ,        0        ,        0     ;...
            0     ,        0        ,        0     ;... % dAdT1s
            0     ,     1/T1s^2     ,   -m0s/T1s^2 ;...
            0     ,        0        ,        0     ;...
            0     ,        0        ,        0     ;... % dAdT2s
            0     , 4/TRF/TR,        0     ;...
            0     ,        0        ,        0     ];

dydt = A * reshape(y, 3, []);
dydt = dydt(:);

yidx = false(size(y));
yidx([1:24:length(y), 2:24:length(y), 3:24:length(y)]) = true;

dydt(~yidx) = dydt(~yidx) + reshape(dAdx * reshape(y(yidx), 3, []), [], 1);

for iy = 25:48:length(y)
    ti = ((iy-1)/48 - 1);
    if abs(t/TR - ti) < 1/2
%         w  = (1-cos(2*pi * (1/2 - (t/TR - ti))))/2;
        w  = 1;
        
        % Derivative wrt. theta
        dAdth = [2*ct*st*w * (1/T1f - 1/T2f),   -R*st*w*m0f  , -m0f*st*w/T1f;...
                        -R*st*w*m0s         , 0,       0      ;...
                             0              ,        0       ,       0      ];
    
        dAdxth = [       0        ,     -R*st*w     ,   -st*w/T1f   ;... % dAdm0f
                         0        ,        0        ,       0       ;...
                         0        ,        0        ,       0       ;...
                         0        ,        0        ,       0       ;... % dAdm0s
                      -R*st*w     ,        0        ,       0       ;...
                         0        ,        0        ,       0       ;...
                  -2*ct*st*w/T1f^2,        0        , m0f*st*w/T1f^2;... % dAdT1f
                         0        ,        0        ,       0       ;...
                         0        ,        0        ,       0       ;...
                  2*st*ct*w/T2f^2 ,        0        ,       0       ;... % dAdT2f
                         0        ,        0        ,       0       ;...
                         0        ,        0        ,       0       ;...
                         0        ,    -st*w*m0f    ,       0       ;... % dAdR
                     -st*w*m0s    ,        0        ,       0       ;...
                         0        ,        0        ,       0       ;...
                         0        ,        0        ,       0       ;... % dAdT1s
                         0        ,        0        ,       0       ;...
                         0        ,        0        ,       0       ;...
                         0        ,        0        ,       0       ;... % dAdT2s
                         0        , 0,       0       ;...
                         0        ,        0        ,       0       ];
    
        dydt(iy  :iy+23) = dydt(iy  :iy+23) + reshape(dAdth * reshape(y(1:24), 3, []), [], 1);
        dydt(iy+3:iy+23) = dydt(iy+3:iy+23) + dAdxth * y(1:3);
        
        % Derivative wrt. TRF aka. TP
        dAdTP = [0,             0           ,0;...
                 0, T2s*4*w/TRF^2/TR,0 ;...
                 0,             0           ,0];

        dAdxTP = [0,          0           , 0;... % dAdm0f
                  0,          0           , 0;...
                  0,          0           , 0;...
                  0,          0           , 0;... % dAdm0s
                  0,          0           , 0;...
                  0,          0           , 0;...
                  0,          0           , 0;... % dAdT1f
                  0,          0           , 0;...
                  0,          0           , 0;...
                  0,          0           , 0;... % dAdT2f
                  0,          0           , 0;...
                  0,          0           , 0;...
                  0,          0           , 0;... % dAdR
                  0,          0           , 0;...
                  0,          0           , 0;...
                  0,          0           , 0;... % dAdT1s
                  0,          0           , 0;...
                  0,          0           , 0;...
                  0,          0           , 0;... % dAdT2s
                  0, -4*w/TRF^2/TR, 0;...
                  0,          0           , 0];
              
        dydt(iy+24:iy+47) = dydt(iy+24:iy+47) + reshape(dAdTP * reshape(y(1:24), 3, []), [], 1);
        dydt(iy+27:iy+47) = dydt(iy+27:iy+47) + dAdxTP * y(1:3);
    end    
end
end