function dydt = radial_MT_ODE(t,y, theta_t, TRF_t, TR, m0f, m0s, T1f, T2f, R, T1s, T2s)
%     m0f = 1 - m0s;
    theta = theta_t(t);
    TRF   = TRF_t(t);
    nbar = T2s / TRF / TR;
    
     A    = [-cos(theta)^2/T1f - sin(theta)^2/T2f - R*m0s,         R*cos(theta)*m0f          , m0f*cos(theta)/T1f;...
                       R*cos(theta)*m0s                  , - (1/T1s + R*m0f + nbar*4*theta^2),      m0s/T1s      ;...
                              0                          ,                 0                 ,         0         ];
    

    dAdT1f = [cos(theta)^2/T1f^2, 0, -m0f*cos(theta)/T1f^2;...
                      0         , 0,          0           ;...
                      0         , 0,          0           ];
                    

    dAdT2f = [sin(theta)^2/T2f^2, 0, 0;...
                    0           , 0, 0;...
                    0           , 0, 0];
                  

    dAdR   = [    -m0s      , cos(theta)*m0f, 0;...
              cos(theta)*m0s,      -m0f     , 0;...
                    0       ,        0      , 0];
                  
    dAdT1s = [0,    0   ,      0    ;...
              0, 1/T1s^2, -m0s/T1s^2;...
              0,    0   ,      0    ];
          
    dAdT2s = [0,        0        , 0;...
              0, 4*theta^2/TRF/TR, 0;...
              0,        0        , 0];
          
    dAdm0f = [0, R*cos(theta), cos(theta)/T1f;...
              0,     -R      ,        0      ;...
              0,      0      ,        0      ];

    dAdm0s = [     -R     , 0,   0  ;...
              R*cos(theta), 0, 1/T1s;...
                    0     , 0,   0  ];
                  
%      A    = [-cos(theta)^2/T1f - sin(theta)^2/T2f - R*m0s*cos(theta)^2,         R*cos(theta)*m0f          , m0f*cos(theta)/T1f;...
%                           R*cos(theta)*m0s                    , - (1/T1s + R*m0f + nbar*4*theta^2),       m0s/T1s          ;...
%                                    0                               ,                   0                    ,           0            ];
%     
% 
%     dAdT1f = [cos(theta)^2/T1f^2,    0   , -m0f*cos(theta)/T1f^2;...
%                         0            ,    0   ,            0         ;...
%                         0            ,    0   ,            0              ];
%                     
% 
%     dAdT2f = [sin(theta)^2/T2f^2, 0, 0;...
%                       0              , 0, 0;...
%                       0              , 0, 0];
%                   
% 
%     dAdR   = [-m0s*cos(theta)^2, cos(theta)*m0f, 0;...
%               cos(theta)*m0s,        -m0f        , 0;...
%                       0          ,          0         , 0];
%                   
%     dAdT1s = [0,    0   ,      0    ;...
%               0, 1/T1s^2, -m0s/T1s^2;...
%               0,    0   ,      0    ];
%           
%     dAdT2s = [0,         0            , 0;...
%               0, 4*theta^2/TRF(t)/TR, 0;...
%               0,         0            , 0];
%           
%     dAdm0f = [0, R*cos(theta), cos(theta)/T1f;...
%               0,       -R         ,          0         ;...
%               0,        0         ,          0         ];
% 
%     dAdm0s = [-R*cos(theta)^2, 0,   0  ;...
%               R*cos(theta), 0, 1/T1s;...
%                       0        , 0,   0  ];

                    
    E = [ A    , zeros(3), zeros(3), zeros(3), zeros(3), zeros(3), zeros(3), zeros(3);...
         dAdT1f,    A    , zeros(3), zeros(3), zeros(3), zeros(3), zeros(3), zeros(3);...
         dAdT2f, zeros(3),    A    , zeros(3), zeros(3), zeros(3), zeros(3), zeros(3);...
         dAdR  , zeros(3), zeros(3),    A    , zeros(3), zeros(3), zeros(3), zeros(3);...
         dAdT1s, zeros(3), zeros(3), zeros(3),    A    , zeros(3), zeros(3), zeros(3);...
         dAdT2s, zeros(3), zeros(3), zeros(3), zeros(3),    A    , zeros(3), zeros(3);...
         dAdm0f, zeros(3), zeros(3), zeros(3), zeros(3), zeros(3),    A    , zeros(3);...
         dAdm0s, zeros(3), zeros(3), zeros(3), zeros(3), zeros(3), zeros(3),    A    ];
    
    dydt = E * y;
%     dydt(1,1) = - y(1) * (cos(theta)^2/T1f + sin(theta)^2/T2f + R/m0f) ...
%                 + y(2) * R*cos(theta)/m0s ...
%                 +        m0f*cos(theta)/T1f;
%           
%     dydt(2,1) =   y(1) * R*cos(theta)/m0f ...
%                 - y(2) * (1/T1s + R/m0s + nbar*4*theta^2) ...
%                 +        m0s/T1s;
end